print("my name is Henry")
print("I am from seattle")
print("I go to Seattle Academy")
print(" i have one sibling and one dog")
print("my favorite brekfast is a nutulla crepe with bananas and strawberrys") 
print("my favroite shows is brooklyn99 the office and how i met ur mother")
print("my favrotie movie is intersteller and the first avengers")
print(" now i want to learn about you") 
their_name = input("whats your name")
print(f"hi {their_name}<nice to meet you")                                         
