print ("choose a name")
name = input ("what is your name")
print (" nice to meet you my name is henry")
print ("this class is so boring")
print (f"do you like this class {name} ")
input (" yes or no")
print (" cool cool do you want to play rock paper scissors and you better say yes")
input (" yes or no")
print ("ok im ready but no cheating because no one likes cheaters")
print(" rock papers scissors shoot")
input(" choose what your are doing")
print("haha loser i beat you black whole allways wins")
print(" lets play blackjack")
print ("ok you got a 10 and a 4 so your at 14")
input ("hit or stand")
